In [69]:
#installing necessary libraries
!pip install kaggle
!pip install pandas
!pip install openpyxl

#importing libraries
import pandas as pd

#also importing zipfile for extracting purposes
import zipfile

#importing kaggle library to start downloading the necessary data directly from Kaggle
import kaggle

#also importing openpyxl for exporting the data to an excel file
import openpyxl

Requirement already satisfied: kaggle in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.5.15)
Requirement already satisfied: six>=1.10 in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaggle) (2023.5.7)
Requirement already satisfied: python-dateutil in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaggle) (4.65.0)
Requirement already satisfied: python-slugify in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaggle) (8.0.1)
Requirement already satisfied: urllib3 in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaggle) (2.0.3)
Requirement already satisfied: bleach in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaggle) (6.0.0)
Requirement already satisfied: webencodings in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->kaggle) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->kaggle) (3.4)
Requirement already satisfied: colorama in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from tqdm->kaggle) (0.4.6)
Requirement already satisfied: pandas in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (1.25.1)
Requirement already satisfied: six>=1.5 in c:\users\bedir\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
                                              0.0/250.0 kB ? eta -:--:--
     --------------                          92.2/250.0 kB 2.6 MB/s eta 0:00:01
     -------------------------------------  245.8/250.0 kB 3.7 MB/s eta 0:00:01
     -------------------------------------- 250.0/250.0 kB 2.6 MB/s eta 0:00:00
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2

In [57]:
#downloading starts from Kaggle via Kaggle API
!kaggle datasets download -d hmavrodiev/london-bike-sharing-dataset

london-bike-sharing-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)

In [58]:
#next step is to extract the downloaded data using zipfile
zipfile_name = "london-bike-sharing-dataset.zip"
with zipfile.ZipFile(zipfile_name, 'r') as file:
    file.extractall()

In [59]:
#using pandas dataframe and read the file

bikeshare = pd.read_csv("london_merged.csv")

In [60]:
#using EDA methods to explore the data and get basic information such as data types and column names
bikeshare.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17414 entries, 0 to 17413
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     17414 non-null  object
 1   cnt           17414 non-null  int64
 2   t1            17414 non-null  float64
 3   t2            17414 non-null  float64
 4   hum           17414 non-null  float64
 5   wind_speed    17414 non-null  float64
 6   weather_code  17414 non-null  float64
 7   is_holiday    17414 non-null  float64
 8   is_weekend    17414 non-null  float64
 9   season        17414 non-null  float64
dtypes: float64(8), int64(1), object(1)
memory usage: 1.3+ MB

In [61]:
#gathering further information
bikeshare.shape

(17414, 10)

In [62]:
#presenting it as a table quickly
bikeshare

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...
17409,2017-01-03 19:00:00,1042,5.0,1.0,81.0,19.0,3.0,0.0,0.0,3.0
17410,2017-01-03 20:00:00,541,5.0,1.0,81.0,21.0,4.0,0.0,0.0,3.0
17411,2017-01-03 21:00:00,337,5.5,1.5,78.5,24.0,4.0,0.0,0.0,3.0
17412,2017-01-03 22:00:00,224,5.5,1.5,76.0,23.0,4.0,0.0,0.0,3.0
17413,2017-01-03 23:00:00,139,5.0,1.0,76.0,22.0,2.0,0.0,0.0,3.0

In [63]:
#choosing new column names for efficiency purposes
new_cols_dict = {
    'timestamp':'time',
    'cnt':'count',
    't1':'temp_real_c',
    't2':'temp_feels_like_c',
    'hum':'humidity_percent',
    'wind_speed':'wind_speed_kph',
    'weather_code':'weather',
    'is_holiday':'is_holiday',
    'is_weekend':'is_weekend',
    'season':'season'
}

#updating the names with the new ones
bikeshare.rename(new_cols_dict, axis=1, inplace=True)

In [64]:
#checking for unique values in specific columns(weather)
bikeshare.weather.value_counts()

#results show there are 6150 values for 1.0, 4034 values for 2.0, 3551 values for 3.0, etc.

weather
1.0     6150
2.0     4034
3.0     3551
7.0     2141
4.0     1464
26.0      60
10.0      14
Name: count, dtype: int64

In [65]:
#humidity values need to be converted to a percentage value
bikeshare.humidity_percent = bikeshare.humidity_percent / 100

In [66]:
#for ease of use, analysis, and efficiency purposes,
#it is best to create dictionaries for season and weather and change the values(integers) for actual corresponding values
season_dict = {
    '0.0':'spring',
    '1.0':'summer',
    '2.0':'autumn',
    '3.0':'winter'
}

weather_dict = {
    '1.0':'Clear',
    '2.0':'Scattered Clouds',
    '3.0':'Broken Clouds',
    '4.0':'Cloudy',
    '7.0':'Rain',
    '10.0':'Rain with Thunderstorm',
    '26.0':'Snowfall'
}

#updating the columns
bikeshare.season = bikeshare.season.astype(str)
#renaming
bikeshare.season = bikeshare.season.map(season_dict)

#updating the columns
bikeshare.weather = bikeshare.weather.astype(str)
#renaming
bikeshare.weather = bikeshare.weather.map(weather_dict)

In [67]:
#validating the actions by looking at the first 10 rows
bikeshare.head(10)

,time,count,temp_real_c,temp_feels_like_c,humidity_percent,wind_speed_kph,weather,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,0.930,6.0,Broken Clouds,0.0,1.0,winter
1,2015-01-04 01:00:00,138,3.0,2.5,0.930,5.0,Clear,0.0,1.0,winter
2,2015-01-04 02:00:00,134,2.5,2.5,0.965,0.0,Clear,0.0,1.0,winter
3,2015-01-04 03:00:00,72,2.0,2.0,1.000,0.0,Clear,0.0,1.0,winter
4,2015-01-04 04:00:00,47,2.0,0.0,0.930,6.5,Clear,0.0,1.0,winter
5,2015-01-04 05:00:00,46,2.0,2.0,0.930,4.0,Clear,0.0,1.0,winter
6,2015-01-04 06:00:00,51,1.0,-1.0,1.000,7.0,Cloudy,0.0,1.0,winter
7,2015-01-04 07:00:00,75,1.0,-1.0,1.000,7.0,Cloudy,0.0,1.0,winter
8,2015-01-04 08:00:00,131,1.5,-1.0,0.965,8.0,Cloudy,0.0,1.0,winter
9,2015-01-04 09:00:00,301,2.0,-0.5,1.000,9.0,Broken Clouds,0.0,1.0,winter

In [70]:
#exporting the final state of the data into excel for visualization
#naming the file 'london_bikeshare_final.xlsx'
bikeshare.to_excel('london_bikeshare_final.xlsx', sheet_name='Data')